language: elixir

# Default Elixir and OTP versions
elixir: '1.6'
otp_release: '20.3'

cache:
  directories:
    $HOME/.mix
    $HOME/.pltcache

script:
  - mix test
  - (cd interop && mix deps.get && mix run script/run.exs)
  # Released inch_ex does not support Elixir 1.7 yet:
  # https://github.com/rrrene/inch_ex/issues/60
  - '[[ "$TRAVIS_ELIXIR_VERSION" = 1.7 ]] || mix inch.report'
  # mix format not available on Elixir 1.4/1.5
  - '[[ "$TRAVIS_ELIXIR_VERSION" =~ 1.[4-5] ]] || mix format --check-formatted'

jobs:
  include:
    - elixir: '1.4'
    - elixir: '1.5'
    - elixir: '1.6'
    - elixir: '1.7'
      otp_release: '21.1'

    # Dialyxer build
    - env: [DIALYZER=1] # So we can see this is the dialyzer build in the matrix
      # FIXME: Elixir 1.6.6's logger seems to fail Dialyzer with OTP/20.
      otp_release: '21.1'
      before_script: travis_wait .ci/build-plt-cache.sh
      script: mix dialyzer --halt-exit-status
